import type { Metadata } from "next";
import { getContent } from "@/data/content";
import { defaultLocale, type Locale, localePath, locales, otherLocale, type PageKey } from "./i18n";
import { siteName } from "./site";

/**
 * Per-page metadata: localized title and description, canonical URL and hreflang alternates.
 * A page-level `openGraph` object replaces the segment's one, so the share image generated by
 * `[lang]/opengraph-image` is referenced explicitly.
 */
export function buildPageMetadata(locale: Locale, page: PageKey): Metadata {
  const { meta } = getContent(locale);
  const { title, description } = meta.pages[page];
  const fullTitle = page === "home" ? title : `${title} · ${siteName}`;
  const url = localePath(locale, page);
  const image = {
    url: `/${locale}/opengraph-image`,
    width: 1200,
    height: 630,
    alt: `${siteName} — ${meta.jobTitle}`,
  };

  return {
    title: page === "home" ? { absolute: title } : title,
    description,
    alternates: {
      canonical: url,
      languages: {
        ...Object.fromEntries(locales.map((code) => [code, localePath(code, page)])),
        "x-default": localePath(defaultLocale, page),
      },
    },
    openGraph: {
      type: "website",
      siteName,
      title: fullTitle,
      description,
      url,
      locale: meta.ogLocale,
      alternateLocale: getContent(otherLocale(locale)).meta.ogLocale,
      images: [image],
    },
    twitter: { card: "summary_large_image", title: fullTitle, description, images: [image] },
  };
}
